kind: ConfigMap
apiVersion: v1
metadata:
  name: breakglass-configmap
data:
  config: |-
    global:
      whitelist:
        - jason@jasonstillerman.com
        - mary@jasonstillerman.com

      permissions:
        - roles/iam.securityReviewer
        - roles/iam.securityAdmin

      notify:
        chatrooms:
          - https://chat.googleapis.com/v1/spaces/AAAAEKxjxdw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=CrAthWtq-lpwJCltF6i-XZqGKnZQhu1FITVVRPMMlTU%3D
          - https://chat.googleapis.com/v1/spaces/AAAAPEjt27o/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=ZYXNYICkcW76G3NiwoA2ryiTgNkwWHroGVuOfR4jW-4%3D
        emails:
          - jason.t.stillerman@gmail.com
          - js.skate.board@gmail.com

    mongodb-277417:
      whitelist:
        - bob@jasonstillerman.com

      blacklist:
        - jason@jasonstillerman.com

      permissions:
        - roles/iam.mongodbSpecific

      notify:
        chatrooms:
          - https://specific.chatroom.for.this.proj/asdf
        emails:
          - jtstille@uvm.edu

    # OAuthClientId: 250953512740-duat8ikq7jcf4jghhs6ql1mm9b7kch1j
    SendGridKey: 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
    OAuthClientId: 521753087986-hgobsrq4rb7f2k58ji59q7qgnu5mkfs8.apps.googleusercontent.com
    ServiceAccountKey: {
        "type": "service_account",
        "project_id": "breakglass-stillerman",
        "private_key_id": "30a16c756e163cd2b002a699f848559aac0edfdf",
        "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCr5nHp2QQLU1zH\n4zs2RUT0Sna6sfwgFmsOsqjgzex0AaZrc2sx4WEgAfNBhsmYZDN9Ct3PatM67wCj\n1pTKiK+O4BPan2hFidQXJsPK+aL2BXuBNrRtQAFJa92sdtrMrXgpEctn4p/hoJO7\nbqwZqyBmXglZe2yxJxNy75q9F8dFqQ9B6kOne09H9/p4F/Y5jF7ar+03+DxadJUu\neOxsRHH8ClBL1Z+Ry5FHrrzoljc1n2Sixa4unWSHrSOouqyVzteaVX7OGO0RoSk7\n6EPjXi6UmRmkKYGDJ+PMoo22qVJXHPWwYThBLkBB+vDevBUxZvVv2t/SpcHtOmqU\nlrFKWA3ZAgMBAAECggEAGieccnOyEVUUO1egFUBR3weLbBmTnoA6tshJOLcsQHRV\n0WiEyVic8gVJ8VDkUHsCeIaUPDBpRkDCLKuEBRLp/0epzaxObbIsYn9j7/iuqlco\nNP9RUYQZDgZK+qg030qPi1QpSjupjudjQvPyXI90hQ7Oxl4oqgWjiGvbc+TvzXHN\nSDdEVnO0Fp5iyt1qw8TSTaq1pCqngEQECfNRYHcV0vmWS5p0p5Z+RSUFutKr0jSl\nnOdb2HwKoLWBU4+dOQNjCeVaX/FAWDwKAgrNXENEFksF0qLnYztBiTBV2UNhS2j3\nsYb7mm6uZZUa81xJ9DWyEkIDxRQIOiz03uq5tbOq9wKBgQDUxztINueWW+EcyM70\nRrorXMRfpFcTcGhFzJAFzaDKo828KgGnkMztGUc7SUReoQaFIjAGk7lWJD2RuHfH\nsZ5Npig2dCTlaMJj6pYjLA9gjepV61eBmp21nMBeAUcI7s+oNaj/bAFjh+VyjYqJ\nTfcKTYnHAYUQr+sPcto17PNQLwKBgQDO0X7/ZpA+GznVyKUYDGBj344LHySNAM6S\nNejd5Xj28VqLjWr1eVV4vR0sQ1XVoZauwq5OsKbZNn3Uor4hgKBRiugmkhws5iEd\n6ea9S4dUAAE8kwYJ3bb/uFOvvPOe/owl3aWKmpuBT5DguSnp1uRaGDzkNc9j8fER\n8NohkyS4dwKBgC3WNXkbCsyjQl1XDO4mhlhtBYis+G0hm/TdWnFFmMvOebV9Pxn/\n4YV6GpQ09luESMlJUhs4m4ZpDDJmELeeFcIYdzUz0/bvmGC52ln9Vdqw97hGmHU8\n/5huCiq2D71m5KkR1jQf6jSsw8rnnt5xQzSe+305YJb1rqeHUGapgsjVAoGBAKV3\n85W/p1QpUEJ8/6mX7V66s9iuF/5AUQWl4CP4vqlEPN8+S/8ODpZFKBwL25bKa9Zy\nqCcJKtTKxi3j7x663ImhC1Agwi4iCQj35MY6sZFBV7vxHXmzTACYp0wJbxkcK2D4\nTsPwIs54rD8/pgsTBSwYDE/BxaX/IpLqEnueUFjNAoGAaEM6t1AnIT9WNEcyFYqp\nsnHfh2zAO1RL7opOutHr3PFrY9TWSbFroRQlywGR7TAspU0Rdp45IuS0bl0b33LD\nG2psa7I8G9DmJR0oDIcYx0Jnt72UinLVUwFO9wAslebssRKEQ/F8cVaL+BiuHzoZ\npDiGuWHYu5Xd/fCGfUmpZog=\n-----END PRIVATE KEY-----\n",
        "client_email": "sa-breakglass@breakglass-stillerman.iam.gserviceaccount.com",
        "client_id": "101657891165280953848",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sa-breakglass%40breakglass-stillerman.iam.gserviceaccount.com"
      }
